---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 002.
--- DateTime: 2020/8/17 11:45
---

require('actionFun.jClick')
require('actionFun.jSlide')


--动作
MotionClass = {

};

MotionClass.__index = MotionClass;


function Motion(page,btn)
    local new ={};
    setmetatable(new,MotionClass);
    new.action_page = page;
    new.action_btn = btn;
    new.orders ={};-- 片段序列;

    if btn then new.name = btn[1] else new.name = page.name; end

    new.action_fre  = nil; --动作频率
    new.action_pre  = nil; --动作间隔
    new.action_slide_speed  = nil; --滑动速度
    new.action_lastTime  = nil; -- 上次执行时间
    new.beforeFun = nil; --执行动作前回调
    new.afterFun = nil; --执行动作后回调
    new.uncheckFun = nil; -- 当特征点没找到的时候回调

    return new;
end

--- reality Motion  click and slide
function MotionClass:click(...)
    self.orders[#self.orders+1] = jClick.new(...);
    return self;
end

function MotionClass:ps(ps)
    self._J_PAGE_SLEEP = ps;
    return self;
end

function MotionClass:slide(...)
    self.orders[#self.orders+1] = jSlide.new(...);
    return self;
end
function MotionClass:fun(fun)
    self.orders[#self.orders+1] = fun;
    return self;
end



function MotionClass:pre(fun)
    self.action_pre_fun = fun;
    return self;
end

function MotionClass:before(fun)
    self.beforeFun = fun;
    return self;
end

function MotionClass:uncheck(fun)
    self.uncheckFun = fun;
    return self;
end

function MotionClass:after(fun)
    self.afterFun = fun;
    return self;
end

function MotionClass:p(ms)
    self.action_pre = ms;
    return self;
end

function MotionClass:speed(spe)
    self.action_slide_speed = spe;
    return self;
end

function MotionClass:f(...)
    self.action_fre = {...};
    return self;
end
